name: Kubernetes CI/CD

on:
  push:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t flask-app .

      - name: Test Deployment
        run: |
          kubectl kustomize ./k8s/overlays/dev > manifests.yaml
          kubectl apply -f manifests.yaml --dry-run=server
          echo "Validation successful - ready for real cluster deployment!"

      - name: Upload Manifests
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-manifests
          path: manifests.yaml