name: CI/CD

on: [push]

permissions:
  contents: read
  actions: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint YAML files
        run: |
          sudo apt-get install -y yamllint  # System package (no pip needed)
          yamllint -d relaxed ./k8s/

      - name: Build and Validate Manifests
        run: |
          kubectl kustomize k8s/overlays/dev > manifests.yaml
          kubectl apply -f manifests.yaml --dry-run=server
          cat manifests.yaml

      - name: Upload Manifests
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-manifests
          path: manifests.yaml