name: Kubernetes CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test Docker Build
        run: docker build -t flask-app .

      - name: Check Kustomize Structure
        run: |
          echo "Validating base configuration..."
          test -f k8s/base/deployment.yaml
          test -f k8s/base/service.yaml
          test -f k8s/base/kustomization.yaml

          echo "Validating dev overlay..."
          test -f k8s/overlays/dev/kustomization.yaml

      - name: Generate Manifests
        run: |
          echo "---" > manifests.yaml
          cat k8s/base/deployment.yaml >> manifests.yaml
          echo "---" >> manifests.yaml
          cat k8s/base/service.yaml >> manifests.yaml
          echo "Manifests combined successfully!"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-configs
          path: |
            manifests.yaml
            k8s/