name: CI/CD

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint YAML files
        run: |
          pip install yamllint
          yamllint -d relaxed ./k8s/

      - name: Build Manifests
        run: |
          kubectl kustomize k8s/overlays/dev > manifests.yaml
          cat manifests.yaml

      - name: Validate Manifests
        run: kubectl apply -f manifests.yaml --dry-run=server

      - name: Upload Manifests
        uses: actions/upload-artifact@v3
        with:
          name: kubernetes-manifests
          path: manifests.yaml