name: CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Kustomize
      run: |
        curl -sLo kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/latest/download/kustomize_linux_amd64.tar.gz
        tar -xzf kustomize.tar.gz
        chmod +x kustomize
        sudo mv kustomize /usr/local/bin/

    - name: Validate Kubernetes Manifests
      run: |
        echo "Validating base configuration..."
        kustomize build ./k8s/base > manifest.yaml
        cat manifest.yaml  
        rm manifest.yaml

        echo "Validating dev overlay..."
        kustomize build ./k8s/overlays/dev > dev-manifest.yaml
        cat dev-manifest.yaml
        rm dev-manifest.yaml
