name: CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Lint K8s Manifests
      run: |
        kubectl kustomize ./k8s/base --validate=true
        kubectl apply -k ./k8s/base --dry-run=server

  deploy-dev:
    needs: lint-test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Simulate Deployment
      run: |
        echo "In a real pipeline:"
        echo "1. docker build -t flask-app ."
        echo "2. docker push flask-app"
        echo "3. kubectl apply -k k8s/overlays/dev"
        
        kubectl kustomize k8s/overlays/dev