name: Basic CI/CD
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Simple Test
        run: |
          echo "✅ GitHub Actions is working!"
          echo "Project structure:"
          ls -R