name: Kubernetes CI

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify Files Exist
        run: |
          echo "Checking required files..."
          ls k8s/base/deployment.yaml
          ls k8s/overlays/dev/kustomization.yaml

      - name: Build Manifests
        run: |
          echo "Generating manifests..."
          kubectl kustomize k8s/overlays/dev > manifests.yaml
          cat manifests.yaml