name: CI/CD

on:
  push:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t flask-app .

      - name: Generate Manifests
        run: |
          kubectl kustomize ./k8s/overlays/dev > manifests.yaml
          echo "Generated manifests:"
          cat manifests.yaml

      - name: Validate Manifests
        run: |
          kubectl apply -f manifests.yaml --dry-run=client
          echo "Client-side validation passed!"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-manifests
          path: manifests.yaml